[package]
name = "transition"
version = "0.0.0"
authors = ["Alex Nebotov <anebotov@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/skillful-alex/ewasm"
edition = "2018"

[dependencies]

[lib]
crate-type = ["cdylib"]

[profile.release]
debug = false
lto = true